import type { AttendanceStatus, PaymentStatus, SifupData, Team } from "./types";

const now = new Date().toISOString();

const playerNames = [
  "Victor",
  "Marcio",
  "Mario Quintana",
  "Mella",
  "Juanjo",
  "Francis",
  "Cooper",
  "Caldera",
  "Alonso",
  "Ale Moran",
  "Amigo Ale M Arquero",
  "Amigo 2 Ale Moran",
  "Stgo Mantelli",
  "Piti",
  "Matias",
  "Beto",
  "Pololo de Francis",
];

function matchPlayer(
  matchId: string,
  index: number,
  name: string,
  paymentStatus: PaymentStatus,
  amountDue: number,
  amountPaid: number,
  note = "",
  team: Team = "none",
  attendanceStatus: AttendanceStatus = "confirmed",
) {
  return {
    id: `${matchId}-player-${index}`,
    matchId,
    name,
    attendanceStatus,
    paymentStatus,
    amountDue,
    amountPaid,
    note,
    team,
    createdAt: now,
    updatedAt: now,
  };
}

export const seedData: SifupData = {
  matches: [
    {
      id: "match-2026-06-30",
      date: "2026-06-30",
      time: "21:00",
      location: "Club Sordos, Av. Jose Pedro Alessandri 1251, Nunoa",
      status: "confirmed",
      totalCost: 35000,
      notes: "Tercer partido. Cancha ya pagada dentro del paquete de 5 canchas.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "match-2026-06-23",
      date: "2026-06-23",
      time: "21:00",
      location: "Club Sordos, Av. Jose Pedro Alessandri 1251, Nunoa",
      status: "played",
      totalCost: 35000,
      notes: "Futbolito martes 23 junio. Segundo partido registrado.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "match-2026-06-09",
      date: "2026-06-09",
      time: "21:00",
      location: "Cancha de los Sordos",
      status: "played",
      totalCost: 35000,
      notes: "Martes 09/06. 3.000 por persona. Primer partido registrado.",
      createdAt: now,
      updatedAt: now,
    },
  ],
  players: playerNames.map((name, index) => ({
    id: `player-${index + 1}`,
    name,
    nickname: name.split(" ")[0],
    phone: "",
    skillLevel: ((index % 5) + 1) as 1 | 2 | 3 | 4 | 5,
    active: true,
    createdAt: now,
    updatedAt: now,
  })),
  matchPlayers: [
    ...[
      ["Victor", "paid", "A", 3500, "pagado fijo"],
      ["Marcio", "paid", "B", 3500, "pagado fijo"],
      ["Mario Quintana", "paid", "A", 3500, "pagado fijo"],
      ["Mella", "paid", "B", 3500, "pagado fijo"],
      ["Juanjo", "paid", "A", 3500, "pagado fijo"],
      ["Francis", "paid", "B", 3500, "pagado fijo"],
      ["Cooper", "paid", "A", 3500, "pagado fijo"],
      ["Stgo Mantelli", "unpaid", "B", 0, ""],
      ["Pololo de Francis", "unpaid", "none", 0, ""],
      ["Beto", "unpaid", "none", 0, ""],
      ["Alonso", "promised", "B", 0, "pago manana"],
    ].map(([name, paymentStatus, team, amountPaid, note], index) =>
      matchPlayer(
        "match-2026-06-30",
        index + 1,
        String(name),
        paymentStatus as PaymentStatus,
        3500,
        Number(amountPaid),
        String(note),
        team as Team,
      ),
    ),
    ...[
      ["Victor", "paid", "A", 3500, "pagado fijo"],
      ["Marcio", "paid", "B", 3500, "pagado fijo"],
      ["Mario Quintana", "paid", "A", 3500, "pagado fijo"],
      ["Mella", "paid", "B", 3500, "pagado fijo"],
      ["Juanjo", "paid", "A", 3500, "pagado fijo"],
      ["Francis", "paid", "B", 3500, "pagado fijo"],
      ["Ale Moran", "promised", "A", 0, "Galleta Cooper por manana"],
      ["Amigo Ale M Arquero", "promised", "B", 0, "Galleta Cooper por manana"],
      ["Amigo 2 Ale Moran", "promised", "A", 0, "Galleta Cooper por manana"],
      ["Stgo Mantelli", "unpaid", "B", 0, ""],
      ["Cooper", "paid", "none", 0, "No puede. Pagado fijo"],
      ["Caldera", "paid", "none", 0, "No puede. Pagado fijo"],
      ["Alonso", "paid", "none", 0, "No puede. Pagado, enfermo"],
    ].map(([name, paymentStatus, team, amountPaid, note], index) =>
      matchPlayer(
        "match-2026-06-23",
        index + 1,
        String(name),
        paymentStatus as PaymentStatus,
        index >= 10 ? 0 : 3500,
        Number(amountPaid),
        String(note),
        team as Team,
        index >= 10 ? "out" : "confirmed",
      ),
    ),
    ...[
      "Marcio",
      "Juanjo",
      "Victor",
      "Cooper",
      "Mario Quintana",
      "Piti",
      "Caldera",
      "Mella",
      "Alonso",
      "Matias",
    ].map((name, index) =>
      matchPlayer(
        "match-2026-06-09",
        index + 1,
        name,
        "paid",
        3000,
        3000,
        index === 9 ? "primo Juanjo" : "",
        index % 2 === 0 ? "A" : "B",
      ),
    ),
  ],
  results: [
    {
      id: "result-2026-06-23",
      matchId: "match-2026-06-23",
      scoreA: 0,
      scoreB: 0,
      winner: "draw",
      notes: "Resultado por completar.",
    },
    {
      id: "result-2026-06-09",
      matchId: "match-2026-06-09",
      scoreA: 0,
      scoreB: 0,
      winner: "draw",
      notes: "Resultado por completar.",
    },
  ],
};
